#!/bin/sh

cd ~


# Log WLR errors and logs to the hyprland log. Recommended
# export HYPRLAND_LOG_WLR=1

# Tell XWayland to use a cursor theme
export XCURSOR_THEME=Adwaita

# Set a cursor size
export XCURSOR_SIZE=24

export XDG_SESSION_TYPE=wayland
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_WAYLAND_DISABLE_WINDOWDEORATION=1

# Example IME Support: fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

exec dbus-launch Hyprland >/dev/null 2>&1   # Sharescreen will work outside systemd
#exec Hyprland  # Screenshare won't work outside systemd

